services:
  front:
    image: hack-front:latest
    # # Порт не обязателен для доступа. Проходит через nginx
    # ports:
    #   - 3000:3000
    networks:
      - atomic
    restart: unless-stopped

  back:
    image: hack-back:latest
    # Порт не обязателен для доступа. Проходит через nginx
    # ports:
    #   - 8000:8000
    environment:
      - POSTGRES_URL=postgresql+asyncpg://postgres:password@db:5432/postgres

      - S3_ENDPOINT=minio:9000
      - S3_ACCESS_KEY=user
      - S3_SECRET_KEY=password
      # - S3_REGION=ru_1
      # - S3_SECURE=False

    networks:
      - atomic
      - backend
    restart: unless-stopped
    depends_on:
      - db
      - minio
      #   
      # Передаит видеокарту для нейронной сети
      #   volumes:
      #     - ./best.pt:/app/best.pt
      #   deploy:
      #     resources:
      #       reservations:
      #         devices:
      #           - driver: nvidia
      #             count: 1
      #             capabilities: [gpu]

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    # ports:
    #   - 5432:5432
    networks:
      - backend


  minio:
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    restart: unless-stopped
    command: server --address ":9000" --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9001:9001"
      # - "13950:9000"
    networks:
      - backend


  nginx:
    image: nginx:latest
    environment:
      - PUID=1000
      - PGID=1000

      - SERVER_DOMAIN=localhost
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - atomic

networks:
  atomic:
  backend:
    