src_dir: "data"
mapping: "class_map_animal.txt"
device: cpu
dst_save_table: "data/table.csv"

detector:
  weights: "weights/detection/yolov8n.pt"
  batch_size: 1
  iou: 0.45
  conf: 0.4
  imgsz:
    - 640
    - 640

classificator:
  weights: "weights/classification/efficientnet_b0.pt"
  batch_size: 8
  imgsz:
    - 768
    - 768
